---
kind: "operation"
client: "rug-cli 0.33.4"
generator:
  name: "NewSpringBootRestService"
  group: "atomist"
  artifact: "spring-rugs"
  version: "0.12.0"
  origin:
    repo: "https://github.com/atomist/spring-rugs.git"
    branch: "6b9204311de6e06c390e9feddbeb413f57fa32c4"
    sha: "6b92043"
  parameters:
    - "artifactId": "springbootpoc"
    - "groupId": "io.thinkd.poc"
    - "version": "0.0.1-SNAPSHOT"
    - "description": "SpringBoot project"
    - "rootPackage": "io.thinkd.springbootpoc"
    - "serviceClassName": "SpringBootPocProject"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddNexusDistributionEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"
  parameters:
    - "nexusUrl": "http://192.168.2.15:10081"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddDockerEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"
  parameters:
    - "dockerRepositoryUrl": "192.168.2.15:10082"
    - "artifactId": "springbootpoc"
    - "version": "0.0.1-SNAPSHOT"
    - "sonarUrl": "http://192.168.2.15:9091"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddKubernetesEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"
  parameters:
    - "artifactId": "springbootpoc"
    - "dockerRepositoryUrl": "192.168.2.15:10082"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddJenkinsfileEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"
  parameters:
    - "artifactId": "springbootpoc"
    - "groupId": "io.thinkd.poc"
    - "notificationsUrl": "http://48e78108.ngrok.io/notifications/jenkins/"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddJacocoEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"
  parameters:
    - "rootPackage": "io.thinkd.springbootpoc"
    - "serviceClassName": "SpringBootPocProject"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "AddSeleniumEditor"
  group: "thinkd"
  artifact: "circuit-springboot"
  version: "0.0.1"

