apiVersion: v1
kind: Pod
metadata:
  name: springbootpoc-pod
  labels:
    name: springbootpoc
spec:
  containers:
    - image: 192.168.2.15:10082/springbootpoc:latest
      name: springbootpoc
      imagePullPolicy: Always
  imagePullSecrets:
    - name: nexus